import { addEvent, database, getCase } from "@/lib/cases-db";
import { apiJson, apiOptions } from "@/lib/api-response";
import { hasValidAdminCode } from "@/lib/admin-access";
import { adminPositions } from "@/lib/school";
export const runtime = "edge";
export function OPTIONS(request: Request) { return apiOptions(request); }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let input: Record<string, unknown>; try { input = await request.json(); } catch { return apiJson({ error: "Format tidak sah." }, request, { status: 400 }); }
  if (!(await hasValidAdminCode(request.headers.get("X-Access-Code") || ""))) return apiJson({ error: "Akses Pentadbir diperlukan." }, request, { status: 403 });
  const adminId = String(input.adminId || ""); const adminName = String(input.adminName || "").trim(); const position = String(input.position || ""); const decision = String(input.decision || ""); const notes = String(input.notes || "").trim();
  if (!adminPositions.includes(position as never) || !["acknowledged", "further_action"].includes(decision) || notes.length > 1500) return apiJson({ error: "Maklumat pengesahan Pentadbir tidak lengkap." }, request, { status: 400 });
  try { const [teacher, record] = await Promise.all([database().prepare("SELECT id, name FROM teachers WHERE id = ? AND active = 1").bind(adminId).first<{id:string;name:string}>(), getCase(id)]); if (!teacher || teacher.name !== adminName) return apiJson({ error: "Identiti Pentadbir tidak sah." }, request, { status: 403 }); if (!record || record.deletedAt) return apiJson({ error: "Kes aktif tidak ditemui." }, request, { status: 404 }); if (!record.disciplineActions.length) return apiJson({ error: "Guru Disiplin perlu merekodkan tindakan awal dahulu." }, request, { status: 409 }); const now = new Date().toISOString(); const next = decision === "acknowledged" ? "green" : "yellow"; await database().batch([database().prepare("INSERT INTO admin_confirmations (id, case_id, decision, admin_id, admin_name, position, notes, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(crypto.randomUUID(), id, decision, adminId, adminName, position, notes, now), database().prepare("UPDATE cases SET traffic_status = ?, updated_at = ? WHERE id = ?").bind(next, now, id)]); await addEvent(id, adminId, adminName, "PK HEM", "pengesahan_admin", decision === "acknowledged" ? `Kes disahkan / diambil maklum sebagai ${position}. ${notes}` : `Tindakan lanjut diminta sebagai ${position}. ${notes}`, { trafficStatus: record.trafficStatus }, { trafficStatus: next, decision, position }); return apiJson({ record: await getCase(id) }, request); }
  catch (error) { console.error(error); return apiJson({ error: "Pengesahan belum dapat disimpan." }, request, { status: 503 }); }
}
