"use client";

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { BarChart3, CalendarDays, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, FileText, LayoutDashboard, Plus, Printer, Search, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { AuthUser, CaseRecord, SchoolClass } from "@/lib/school";

type LateRecord={id:string;studentId:string;studentName:string;classId:string;className:string;date:string;time:string;reason:string;notes:string;dutyTeacherName:string;createdAt:string;updatedAt:string};
type HemProgram={id:string;name:string;unit:string;date:string;startTime:string;endTime:string;location:string;coordinatorName:string;targetGroup:string;participantCount:number;objective:string;activities:string;impact:string;summary:string;status:"planned"|"ongoing"|"completed";createdAt:string;updatedAt:string};
type HubTab="summary"|"late"|"students"|"follow"|"programs"|"opr";
type Fetcher=(path:string,init?:RequestInit)=>Promise<Response>;
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const statusName={planned:"Dirancang",ongoing:"Sedang Berjalan",completed:"Selesai"};
const trafficName={red:"Belum tindakan",yellow:"Dalam tindakan",green:"Selesai"};

function Pick({value,onChange,placeholder,children}:{value:string;onChange:(value:string)=>void;placeholder:string;children:ReactNode}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{children}</SelectContent></Select>}

export function HemHub({user,classes,cases,authFetch,onOpen,notify}:{user:AuthUser;classes:SchoolClass[];cases:CaseRecord[];authFetch:Fetcher;onOpen:(record:CaseRecord)=>void;notify:(message:string)=>void}){
 const[tab,setTab]=useState<HubTab>("summary"),[late,setLate]=useState<LateRecord[]>([]),[programs,setPrograms]=useState<HemProgram[]>([]),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
 const[lateForm,setLateForm]=useState({studentId:"",date:today(),time:nowTime(),reason:"",notes:""});
 const[programForm,setProgramForm]=useState({name:"",unit:"Disiplin",date:today(),startTime:"",endTime:"",location:"",targetGroup:"",participantCount:"",objective:"",activities:"",impact:"",summary:"",status:"planned"});
 const[selectedProgram,setSelectedProgram]=useState("");
 const pupils=useMemo(()=>classes.flatMap(cls=>cls.students.map(student=>({...student,classId:cls.id,className:cls.name}))).sort((a,b)=>a.name.localeCompare(b.name)),[classes]);
 async function load(){try{const[a,b]=await Promise.all([authFetch("/api/hem?module=late",{cache:"no-store"}),authFetch("/api/hem?module=programs",{cache:"no-store"})]);const ad=await a.json() as {records?:LateRecord[],error?:string};const bd=await b.json() as {records?:HemProgram[],error?:string};if(!a.ok||!b.ok)throw new Error(ad.error||bd.error);setLate(ad.records||[]);setPrograms(bd.records||[]);}catch(e){notify(e instanceof Error?e.message:"Data HEM gagal dimuatkan.");}}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const canManage=user.superAdmin||["discipline","school_admin"].includes(user.activeRole||"");
 async function addLate(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await authFetch("/api/hem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"late",...lateForm})});const d=await r.json() as {record?:LateRecord,error?:string};if(!r.ok||!d.record)throw new Error(d.error);setLate(old=>[d.record!,...old]);setLateForm({studentId:"",date:today(),time:nowTime(),reason:"",notes:""});notify("Rekod lewat hadir berjaya disimpan dan diaudit.");}catch(e){notify(e instanceof Error?e.message:"Rekod gagal disimpan.");}finally{setBusy(false);}}
 async function addProgram(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await authFetch("/api/hem",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"programs",...programForm,participantCount:Number(programForm.participantCount)||0})});const d=await r.json() as {record?:HemProgram,error?:string};if(!r.ok||!d.record)throw new Error(d.error);setPrograms(old=>[d.record!,...old]);setSelectedProgram(d.record.id);setProgramForm({name:"",unit:"Disiplin",date:today(),startTime:"",endTime:"",location:"",targetGroup:"",participantCount:"",objective:"",activities:"",impact:"",summary:"",status:"planned"});notify("Program HEM berjaya disimpan.");}catch(e){notify(e instanceof Error?e.message:"Program gagal disimpan.");}finally{setBusy(false);}}
 async function finishProgram(program:HemProgram){const impact=window.prompt("Catat impak program",program.impact)||program.impact;const summary=window.prompt("Catat rumusan program",program.summary)||program.summary;const r=await authFetch("/api/hem",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"programs",id:program.id,status:"completed",impact,summary})});const d=await r.json() as {record?:HemProgram,error?:string};if(!r.ok||!d.record)return notify(d.error||"Kemas kini gagal.");setPrograms(old=>old.map(item=>item.id===d.record!.id?d.record!:item));notify("Program ditandakan selesai dan sedia dijana sebagai OPR.");}
 const filteredLate=late.filter(item=>!query||[item.studentName,item.className,item.reason,item.dutyTeacherName].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 const filteredCases=cases.filter(item=>!query||[item.student,item.className,item.category,item.reporter].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 const selected=programs.find(item=>item.id===selectedProgram)||programs[0];
 const month=new Date().toISOString().slice(0,7),monthCases=cases.filter(item=>item.date.startsWith(month)).length;
 const classCounts=classes.map(cls=>({name:cls.name,value:cases.filter(item=>item.classId===cls.id||item.participants.some(p=>p.classId===cls.id)).length})).sort((a,b)=>b.value-a.value).slice(0,8);
 const categories=[...new Set(cases.map(item=>item.category))].map(name=>({name,value:cases.filter(item=>item.category===name).length})).sort((a,b)=>b.value-a.value).slice(0,6);
 return <section className="hem-hub">
  <nav className="hem-tabs" aria-label="Modul Pengurusan HEM">{([{id:"summary",label:"Dashboard",icon:<LayoutDashboard/>},{id:"late",label:"Lewat Hadir",icon:<Clock3/>},{id:"students",label:"Murid",icon:<UsersRound/>},{id:"follow",label:"Tindakan / Susulan",icon:<ClipboardCheck/>},{id:"programs",label:"Program HEM",icon:<CalendarDays/>},{id:"opr",label:"Jana OPR",icon:<FileText/>}] as {id:HubTab,label:string,icon:ReactNode}[]).map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>{setTab(item.id);setQuery("");}}>{item.icon}<span>{item.label}</span></button>)}</nav>
  {tab==="summary"&&<><div className="hem-stat-grid"><Stat label="Jumlah Murid" value={pupils.length}/><Stat label="Jumlah Kes" value={cases.length}/><Stat label="Kes Bulan Ini" value={monthCases}/><Stat label="Murid Lewat" value={new Set(late.map(item=>item.studentId)).size}/><Stat label="Belum Selesai" value={cases.filter(item=>item.trafficStatus!=="green").length}/><Stat label="Kes Selesai" value={cases.filter(item=>item.trafficStatus==="green").length}/></div><div className="hem-analytics-grid"><BarPanel title="Kes Mengikut Kelas" data={classCounts}/><BarPanel title="Kesalahan Paling Kerap" data={categories}/></div><section className="hem-panel"><header><div><small>REKOD TERKINI</small><h3>Kes Disiplin Terbaharu</h3></div><button onClick={()=>setTab("follow")}>Lihat semua <ChevronRight/></button></header><CaseRows records={cases.slice(0,6)} onOpen={onOpen}/></section></>}
  {tab==="late"&&<><form className="hem-form" onSubmit={addLate}><header><div><small>REKOD KELEWATAN</small><h3>Tambah Rekod Lewat Hadir</h3><p>Guru bertugas direkodkan secara automatik sebagai {user.name}.</p></div><Clock3/></header><div className="hem-form-grid"><label>Murid<Pick value={lateForm.studentId} onChange={value=>setLateForm({...lateForm,studentId:value})} placeholder="Pilih murid">{pupils.map(p=><SelectItem key={p.id} value={p.id}>{p.name} — {p.className}</SelectItem>)}</Pick></label><label>Tarikh<Input type="date" value={lateForm.date} onChange={e=>setLateForm({...lateForm,date:e.target.value})}/></label><label>Masa tiba<Input type="time" value={lateForm.time} onChange={e=>setLateForm({...lateForm,time:e.target.value})}/></label><label>Sebab lewat<Input value={lateForm.reason} onChange={e=>setLateForm({...lateForm,reason:e.target.value})} placeholder="Contoh: Kenderaan lewat"/></label><label className="wide">Catatan<Textarea value={lateForm.notes} onChange={e=>setLateForm({...lateForm,notes:e.target.value})}/></label></div><Button disabled={busy||!lateForm.studentId||!lateForm.reason}><Plus/>Simpan Rekod Lewat</Button></form><SearchBox value={query} onChange={setQuery} placeholder="Cari murid, kelas, sebab atau guru bertugas..."/><section className="hem-panel"><header><div><small>{filteredLate.length} REKOD</small><h3>Senarai Lewat Hadir</h3></div></header><div className="hem-table-wrap"><table><thead><tr><th>Tarikh / Masa</th><th>Murid</th><th>Sebab</th><th>Guru Bertugas</th></tr></thead><tbody>{filteredLate.map(item=><tr key={item.id}><td>{item.date}<small>{item.time}</small></td><td><strong>{item.studentName}</strong><small>{item.className}</small></td><td>{item.reason}<small>{item.notes}</small></td><td>{item.dutyTeacherName}</td></tr>)}</tbody></table></div>{!filteredLate.length&&<Empty text="Belum ada rekod lewat hadir."/>}</section></>}
  {tab==="students"&&<><SearchBox value={query} onChange={setQuery} placeholder="Cari nama murid atau kelas..."/><section className="hem-panel"><header><div><small>DIREKTORI MURID</small><h3>Senarai Murid dan Rekod Pemantauan</h3></div><span>{pupils.length} murid</span></header><div className="hem-table-wrap"><table><thead><tr><th>Nama Murid</th><th>Kelas</th><th>Kes</th><th>Lewat</th><th>Status</th></tr></thead><tbody>{pupils.filter(p=>!query||`${p.name} ${p.className}`.toLowerCase().includes(query.toLowerCase())).map(p=>{const caseCount=cases.filter(c=>c.studentId===p.id||c.participants.some(x=>x.studentId===p.id)).length,lateCount=late.filter(x=>x.studentId===p.id).length;return <tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.className}</td><td>{caseCount}</td><td>{lateCount}</td><td><span className={`hem-signal ${caseCount||lateCount?"attention":"clear"}`}>{caseCount||lateCount?"Perlu dipantau":"Tiada rekod"}</span></td></tr>})}</tbody></table></div></section></>}
  {tab==="follow"&&<><SearchBox value={query} onChange={setQuery} placeholder="Cari murid, kelas, kesalahan atau pelapor..."/><div className="hem-follow-summary"><span><b>{cases.filter(x=>x.trafficStatus==="red").length}</b> Belum tindakan</span><span><b>{cases.filter(x=>x.trafficStatus==="yellow").length}</b> Dalam tindakan</span><span><b>{cases.filter(x=>x.trafficStatus==="green").length}</b> Selesai</span></div><section className="hem-panel"><header><div><small>PANTAUAN KES</small><h3>Tindakan dan Susulan</h3></div></header><CaseRows records={filteredCases} onOpen={onOpen}/></section></>}
  {tab==="programs"&&<>{canManage&&<form className="hem-form program-form" onSubmit={addProgram}><header><div><small>AKTIVITI HAL EHWAL MURID</small><h3>Tambah Program HEM</h3></div><CalendarDays/></header><div className="hem-form-grid"><label>Nama program<Input value={programForm.name} onChange={e=>setProgramForm({...programForm,name:e.target.value})}/></label><label>Unit HEM<Input value={programForm.unit} onChange={e=>setProgramForm({...programForm,unit:e.target.value})}/></label><label>Tarikh<Input type="date" value={programForm.date} onChange={e=>setProgramForm({...programForm,date:e.target.value})}/></label><label>Tempat<Input value={programForm.location} onChange={e=>setProgramForm({...programForm,location:e.target.value})}/></label><label>Masa mula<Input type="time" value={programForm.startTime} onChange={e=>setProgramForm({...programForm,startTime:e.target.value})}/></label><label>Masa tamat<Input type="time" value={programForm.endTime} onChange={e=>setProgramForm({...programForm,endTime:e.target.value})}/></label><label>Sasaran<Input value={programForm.targetGroup} onChange={e=>setProgramForm({...programForm,targetGroup:e.target.value})}/></label><label>Bilangan peserta<Input type="number" min="0" value={programForm.participantCount} onChange={e=>setProgramForm({...programForm,participantCount:e.target.value})}/></label><label className="wide">Objektif<Textarea value={programForm.objective} onChange={e=>setProgramForm({...programForm,objective:e.target.value})}/></label><label className="wide">Aktiviti<Textarea value={programForm.activities} onChange={e=>setProgramForm({...programForm,activities:e.target.value})}/></label></div><Button disabled={busy||programForm.name.length<3||!programForm.location}><Plus/>Simpan Program</Button></form>}<div className="program-card-grid">{programs.map(program=><article key={program.id}><header><span>{program.unit}</span><em className={`program-${program.status}`}>{statusName[program.status]}</em></header><h3>{program.name}</h3><p><CalendarDays/> {program.date} · {program.startTime||"Masa belum ditetapkan"}</p><p><UsersRound/> {program.targetGroup||"Sasaran belum dinyatakan"} · {program.participantCount} peserta</p><small>Penyelaras: {program.coordinatorName}</small><div><Button variant="outline" onClick={()=>{setSelectedProgram(program.id);setTab("opr")}}><FileText/>OPR</Button>{canManage&&program.status!=="completed"&&<Button onClick={()=>void finishProgram(program)}><CheckCircle2/>Tandakan Selesai</Button>}</div></article>)}{!programs.length&&<Empty text="Belum ada Program HEM direkodkan."/>}</div></>}
  {tab==="opr"&&<><section className="hem-opr-tools"><label>Pilih program<Pick value={selected?.id||""} onChange={setSelectedProgram} placeholder="Pilih program">{programs.map(program=><SelectItem key={program.id} value={program.id}>{program.name}</SelectItem>)}</Pick></label><Button disabled={!selected} onClick={()=>window.print()}><Printer/>Cetak / Simpan PDF</Button></section>{selected?<Opr program={selected}/>:<Empty text="Pilih atau tambah program untuk menjana OPR HEM."/>}</>}
 </section>
}

function Stat({label,value}:{label:string;value:number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function BarPanel({title,data}:{title:string;data:{name:string,value:number}[]}){const max=Math.max(1,...data.map(x=>x.value));return <section className="hem-panel hem-bars"><header><div><small>ANALISIS</small><h3>{title}</h3></div><BarChart3/></header>{data.map(item=><div key={item.name}><span>{item.name}</span><i><b style={{width:`${item.value/max*100}%`}}/></i><strong>{item.value}</strong></div>)}{!data.length&&<Empty text="Belum ada data untuk dianalisis."/>}</section>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="hem-search"><Search/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function CaseRows({records,onOpen}:{records:CaseRecord[];onOpen:(record:CaseRecord)=>void}){return <div className="hem-case-list">{records.map(record=><button key={record.id} onClick={()=>onOpen(record)}><div><strong>{record.student}</strong><span>{record.className} · {record.category}</span><small>{record.date} · Pelapor: {record.reporter}</small></div><em className={`traffic-${record.trafficStatus}`}>{trafficName[record.trafficStatus]}</em><ChevronRight/></button>)}{!records.length&&<Empty text="Tiada rekod yang sepadan."/>}</div>}
function Empty({text}:{text:string}){return <div className="hem-empty"><ClipboardCheck/><span>{text}</span></div>}
function Opr({program}:{program:HemProgram}){const logo=typeof window!=="undefined"&&window.location.hostname==="fikreyxcode.github.io"?"/hem-smartdisiplin-skrg/sk-ranggu-cutout.png":"/sk-ranggu-cutout.png";return <article className="opr-sheet"><header><img src={logo} alt="Logo SK Ranggu"/><div><small>SEKOLAH KEBANGSAAN RANGGU</small><h2>ONE PAGE REPORT (OPR)</h2><strong>PROGRAM HAL EHWAL MURID (HEM)</strong></div></header><table><tbody><tr><th>Nama Program</th><td>{program.name}</td></tr><tr><th>Unit HEM</th><td>{program.unit}</td></tr><tr><th>Tarikh / Masa</th><td>{program.date} · {program.startTime||"—"}{program.endTime?` – ${program.endTime}`:""}</td></tr><tr><th>Tempat</th><td>{program.location}</td></tr><tr><th>Penyelaras</th><td>{program.coordinatorName}</td></tr><tr><th>Sasaran / Peserta</th><td>{program.targetGroup||"—"} · {program.participantCount} orang</td></tr><tr><th>Objektif</th><td>{program.objective||"—"}</td></tr><tr><th>Aktiviti</th><td>{program.activities||"—"}</td></tr><tr><th>Impak</th><td>{program.impact||"Belum dikemas kini"}</td></tr><tr><th>Rumusan</th><td>{program.summary||"Belum dikemas kini"}</td></tr></tbody></table><footer>SEKOLAH KEBANGSAAN RANGGU · PETI SURAT 842, 91008 TAWAU, SABAH</footer></article>}
