import { addEvent, database, getCase } from "@/lib/cases-db";
import { apiJson, apiOptions } from "@/lib/api-response";
import { hasValidAdminCode, hasValidDisciplineCode } from "@/lib/admin-access";
import { adminPositions, ssdmRecommendationOptions } from "@/lib/school";
export const runtime = "edge";
export function OPTIONS(request: Request) { return apiOptions(request); }

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let input: Record<string, unknown>; try { input = await request.json(); } catch { return apiJson({ error: "Format tidak sah." }, request, { status: 400 }); }
  if (!(await hasValidDisciplineCode(request.headers.get("X-Access-Code") || ""))) return apiJson({ error: "Akses Guru Disiplin diperlukan." }, request, { status: 403 });
  const actorId = String(input.actorId || ""); const actorName = String(input.actorName || "").trim(); const feedback = String(input.pupilParentFeedback || "").trim(); const recommendation = String(input.recommendation || ""); const otherRecommendation = String(input.otherRecommendation || "").trim(); const extraNotes = String(input.extraNotes || "").trim();
  if (!ssdmRecommendationOptions.includes(recommendation as never) || (recommendation === "Lain-lain" && !otherRecommendation) || feedback.length > 2500 || extraNotes.length > 2000) return apiJson({ error: "Maklumat permohonan SSDM tidak lengkap." }, request, { status: 400 });
  try { const [teacher, record] = await Promise.all([database().prepare("SELECT id, name FROM teachers WHERE id = ? AND active = 1").bind(actorId).first<{id:string;name:string}>(), getCase(id)]); if (!teacher || teacher.name !== actorName) return apiJson({ error: "Identiti Guru Disiplin tidak sah." }, request, { status: 403 }); if (!record || record.deletedAt) return apiJson({ error: "Kes aktif tidak ditemui." }, request, { status: 404 }); if (!record.disciplineActions.length) return apiJson({ error: "Rekodkan tindakan Guru Disiplin sebelum memohon kelulusan SSDM." }, request, { status: 409 }); if (record.ssdmRequest && ["pending", "approved"].includes(record.ssdmRequest.status)) return apiJson({ error: "Permohonan SSDM ini masih menunggu atau telah diluluskan." }, request, { status: 409 }); const now = new Date().toISOString(); await database().prepare("INSERT INTO ssdm_requests (id, case_id, pupil_parent_feedback, recommendation, other_recommendation, extra_notes, status, requested_by_id, requested_by_name, requested_at, admin_notes) VALUES (?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, '')").bind(crypto.randomUUID(), id, feedback, recommendation, otherRecommendation, extraNotes, actorId, actorName, now).run(); await addEvent(id, actorId, actorName, "Guru Disiplin", "permohonan_ssdm", `Permohonan kelulusan SSDM dihantar — ${recommendation}${otherRecommendation ? `: ${otherRecommendation}` : ""}.`, null, { recommendation, status: "pending" }); return apiJson({ record: await getCase(id) }, request); }
  catch (error) { console.error(error); return apiJson({ error: "Permohonan SSDM belum dapat disimpan." }, request, { status: 503 }); }
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let input: Record<string, unknown>; try { input = await request.json(); } catch { return apiJson({ error: "Format tidak sah." }, request, { status: 400 }); }
  if (!(await hasValidAdminCode(request.headers.get("X-Access-Code") || ""))) return apiJson({ error: "Akses Pentadbir diperlukan." }, request, { status: 403 });
  const adminId = String(input.adminId || ""); const adminName = String(input.adminName || "").trim(); const position = String(input.position || ""); const decision = String(input.decision || ""); const notes = String(input.notes || "").trim();
  if (!adminPositions.includes(position as never) || !["approved", "rejected", "returned"].includes(decision) || notes.length > 2000) return apiJson({ error: "Keputusan SSDM tidak lengkap." }, request, { status: 400 });
  try { const [teacher, record] = await Promise.all([database().prepare("SELECT id, name FROM teachers WHERE id = ? AND active = 1").bind(adminId).first<{id:string;name:string}>(), getCase(id)]); if (!teacher || teacher.name !== adminName) return apiJson({ error: "Identiti Pentadbir tidak sah." }, request, { status: 403 }); if (!record?.ssdmRequest || record.ssdmRequest.status !== "pending") return apiJson({ error: "Tiada permohonan SSDM yang sedang menunggu." }, request, { status: 409 }); const now = new Date().toISOString(); await database().prepare("UPDATE ssdm_requests SET status = ?, decided_by_id = ?, decided_by_name = ?, decided_by_position = ?, decided_at = ?, admin_notes = ? WHERE id = ? AND status = 'pending'").bind(decision, adminId, adminName, position, now, notes, record.ssdmRequest.id).run(); await addEvent(id, adminId, adminName, "PK HEM", "keputusan_ssdm", `Keputusan SSDM oleh ${position}: ${decision}. ${notes}`, { status: "pending" }, { status: decision }); return apiJson({ record: await getCase(id) }, request); }
  catch (error) { console.error(error); return apiJson({ error: "Keputusan SSDM belum dapat disimpan." }, request, { status: 503 }); }
}
